In [1]:
import pandas as pd
import numpy as np

In [2]:
gdp_df= pd.read_csv("gdp_year.csv")
gdp_df

    date  level-current  level-chained  change-current  change-chained
0   1930           92.2          966.7           -16.0            -6.4
1   1931           77.4          904.8           -23.1           -12.9
2   1932           59.5          788.2            -4.0            -1.2
3   1933           57.2          778.3            16.9            10.8
4   1934           66.8          862.2            11.1             8.9
..   ...            ...            ...             ...             ...
82  2012        16155.3        15354.6             3.6             1.8
83  2013        16691.5        15612.2             4.4             2.5
84  2014        17427.6        16013.3             4.0             2.9
85  2015        18120.7        16471.5             2.7             1.6
86  2016        18624.5        16716.2             4.2             2.2

[87 rows x 5 columns]

In [3]:
presidents_df= pd.read_csv("all_us_presidents.csv")
presidents_df.tail(10)

     Years (after inauguration)       President       Party
217                        2004  George W. Bush  Republican
218                        2005  George W. Bush  Republican
219                        2006  George W. Bush  Republican
220                        2007  George W. Bush  Republican
221                        2008  George W. Bush  Republican
222                        2009    Barack Obama    Democrat
223                        2010    Barack Obama    Democrat
224                        2011    Barack Obama    Democrat
225                        2012    Barack Obama    Democrat
226                        2013    Barack Obama    Democrat

In [29]:
# get values for the years after 2013 for year column
add_years_after_inaguration = presidents_df["Years (after inauguration)"].iloc[-1]

# adding new rows that include Years (after inauguration), name of president and party
new_rows = {
    "Years (after inauguration)": [add_years_after_inaguration + i for i in range(1, 12)],
    "President": ['Barack Obama'] * 3 + ['Donald Trump'] * 4 + ['Joe Biden'] * 4,
    "Party": ['Democrat'] * 3 + ['Republican'] * 4 + ['Democrat'] * 4
}

#new_rows

In [30]:
updated_pres_df =pd.DataFrame(new_rows)
updated_pres_df

    Years (after inauguration)     President       Party
0                         2014  Barack Obama    Democrat
1                         2015  Barack Obama    Democrat
2                         2016  Barack Obama    Democrat
3                         2017  Donald Trump  Republican
4                         2018  Donald Trump  Republican
5                         2019  Donald Trump  Republican
6                         2020  Donald Trump  Republican
7                         2021     Joe Biden    Democrat
8                         2022     Joe Biden    Democrat
9                         2023     Joe Biden    Democrat
10                        2024     Joe Biden    Democrat

In [31]:
cleaned_pres_df=pd.concat([presidents_df,updated_pres_df])
cleaned_pres_df.tail(15)

     Years (after inauguration)     President       Party
223                        2010  Barack Obama    Democrat
224                        2011  Barack Obama    Democrat
225                        2012  Barack Obama    Democrat
226                        2013  Barack Obama    Democrat
0                          2014  Barack Obama    Democrat
1                          2015  Barack Obama    Democrat
2                          2016  Barack Obama    Democrat
3                          2017  Donald Trump  Republican
4                          2018  Donald Trump  Republican
5                          2019  Donald Trump  Republican
6                          2020  Donald Trump  Republican
7                          2021     Joe Biden    Democrat
8                          2022     Joe Biden    Democrat
9                          2023     Joe Biden    Democrat
10                         2024     Joe Biden    Democrat

In [32]:
cleaned_pres_df.to_csv("cleaned_pres_df.csv", index=False)